# -*- coding: utf-8 -*-
"""Menu principale del gestionale."""

from .app_sections import (
    SECTION_PAZIENTI, SECTION_PNEV, SECTION_VISION, SECTION_SEDUTE,
    SECTION_OSTEOPATIA, SECTION_COUPON, SECTION_DASHBOARD,
    SECTION_RELAZIONI, SECTION_EVOLUTIVA, SECTION_PRIVACY,
    SECTION_DEBUG, SECTION_IMPORT, SECTION_GAZE, SECTION_READING_DOM,
    SECTION_UTENTI, SECTION_TERAPIA,
    SECTION_NPS_OLD, SECTION_PIANO_VT, SECTION_REPORT_PDF,
    SECTION_DEM, SECTION_KD, SECTION_EXPORT, SECTION_SEED_DEMO,
    SECTION_NPS, SECTION_DSA, SECTION_TEST_PSY, SECTION_FE,
    SECTION_SAAS_ADMIN, SECTION_MIO_STUDIO,
    SECTION_SOMMINISTRAZIONE,
)

SECTION_LENTI_CONTATTO = "👁️ Lenti a contatto"
SECTION_PHOTOREF = "📸 Photoref AI"

BASE_SECTIONS = [
    SECTION_DASHBOARD,
    SECTION_PAZIENTI,
    SECTION_PNEV,
    SECTION_VISION,
    SECTION_LENTI_CONTATTO,
    SECTION_PHOTOREF,
    SECTION_READING_DOM,
    SECTION_TERAPIA,
    SECTION_SEDUTE,
    SECTION_OSTEOPATIA,
    SECTION_COUPON,
    SECTION_RELAZIONI,
    SECTION_EVOLUTIVA,
    SECTION_PRIVACY,
    SECTION_DEBUG,
    SECTION_IMPORT,
    SECTION_GAZE,
    # ── Valutazioni cognitive / DSA / PSY ──────────────────────────
    SECTION_NPS,
    SECTION_DSA,
    SECTION_FE,
    SECTION_SOMMINISTRAZIONE,
    SECTION_TEST_PSY,
    # ── Strumenti VT e report ───────────────────────────────────────
    SECTION_DEM,
    SECTION_KD,
    SECTION_PIANO_VT,
    SECTION_REPORT_PDF,
    SECTION_EXPORT,
    # ── Studio ─────────────────────────────────────────────────────
    SECTION_MIO_STUDIO,
]

ADMIN_SECTIONS = [
    SECTION_UTENTI,
    SECTION_SEED_DEMO,
    SECTION_SAAS_ADMIN,
]

SECTION_DIAGNOSTICA_UDITIVA = "🔉 Diagnostica Uditiva"
SECTION_STIMOLAZIONE_PASSIVA = "🎵 Stimolazione Passiva"


def build_sections(is_admin: bool, app_mode: str) -> list[str]:
    sections = list(BASE_SECTIONS)
    if is_admin:
        sections.extend(ADMIN_SECTIONS)
    sections.append(SECTION_DIAGNOSTICA_UDITIVA)
    sections.append(SECTION_STIMOLAZIONE_PASSIVA)
    return sections
