# -*- coding: utf-8 -*-
"""
Anamnesi Visiva / Optometrica — The Organism
Scheda di anamnesi specifica per l'area visiva/optometrica, distinta
dall'anamnesi neuroevolutiva (PNEV). Un record per paziente (aggiornabile).

Esposto: render_anamnesi_visiva(conn, paz_id)
"""
from __future__ import annotations
import json
import datetime
import streamlit as st

SINTOMI = [
    "Mal di testa", "Visione sfocata da vicino", "Visione sfocata da lontano",
    "Diplopia (visione doppia)", "Affaticamento visivo", "Fotofobia",
    "Lacrimazione", "Bruciore / occhi rossi",
]
PATOLOGIE_MED = ["Diabete", "Ipertensione", "Allergie", "Tiroide", "Emicrania"]


# ── DB ────────────────────────────────────────────────────────────────
def _ensure_table(conn) -> None:
    cur = conn.cursor()
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS anamnesi_visiva (
            id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            paziente_id  BIGINT NOT NULL REFERENCES Pazienti(id) ON DELETE CASCADE,
            studio_id    BIGINT DEFAULT current_setting('app.current_studio', true)::bigint,
            data_visita  TEXT,
            motivo       TEXT,
            dati_json    JSONB,
            creato_il    TIMESTAMP DEFAULT now(),
            aggiornato_il TIMESTAMP DEFAULT now()
        )
        """
    )
    conn.commit()


def _carica(conn, paz_id: int) -> dict:
    try:
        cur = conn.cursor()
        cur.execute(
            "SELECT dati_json FROM anamnesi_visiva WHERE paziente_id=%s "
            "ORDER BY aggiornato_il DESC, id DESC LIMIT 1",
            (paz_id,),
        )
        row = cur.fetchone()
        if not row:
            return {}
        raw = row["dati_json"] if isinstance(row, dict) else row[0]
        if not raw:
            return {}
        return raw if isinstance(raw, dict) else json.loads(raw)
    except Exception:
        return {}


def _salva(conn, paz_id: int, dati: dict) -> None:
    try:
        cur = conn.cursor()
        cur.execute(
            "SELECT id FROM anamnesi_visiva WHERE paziente_id=%s "
            "ORDER BY aggiornato_il DESC, id DESC LIMIT 1",
            (paz_id,),
        )
        row = cur.fetchone()
        dump = json.dumps(dati, ensure_ascii=False, default=str)
        motivo = dati.get("motivo", "")
        oggi = datetime.date.today().isoformat()

        if row:
            rec_id = int(row["id"] if isinstance(row, dict) else row[0])
            cur.execute(
                "UPDATE anamnesi_visiva SET dati_json=%s::jsonb, motivo=%s, "
                "data_visita=%s, aggiornato_il=now() WHERE id=%s",
                (dump, motivo, oggi, rec_id),
            )
        else:
            cur.execute(
                "INSERT INTO anamnesi_visiva "
                "(paziente_id, data_visita, motivo, dati_json) "
                "VALUES (%s, %s, %s, %s::jsonb)",
                (paz_id, oggi, motivo, dump),
            )
        conn.commit()
        st.success("Anamnesi visiva salvata.")
    except Exception as e:
        try:
            conn.rollback()
        except Exception:
            pass
        st.error(f"Errore nel salvataggio: {e}")


def sintesi_anamnesi(conn, paz_id: int) -> str:
    """Sintesi (markdown) dell'anamnesi visiva per diagnosi/relazione/stampa.
    Restituisce stringa vuota se non c'è anamnesi salvata."""
    try:
        d = _carica(conn, paz_id)
    except Exception:
        return ""
    if not d:
        return ""
    righe = []
    if d.get("motivo"):
        righe.append(f"Motivo della visita: {d['motivo']}")
    sint = list(d.get("sintomi") or [])
    if d.get("sintomi_altro"):
        sint.append(d["sintomi_altro"])
    if sint:
        righe.append("Sintomi: " + ", ".join(sint))
    sv = []
    if d.get("occhiali"):
        sv.append("occhiali: " + d["occhiali"] +
                  (f" ({d['occhiali_dett']})" if d.get("occhiali_dett") else ""))
    if d.get("lac"):
        sv.append("lenti a contatto: " + d["lac"] +
                  (f" ({d['lac_dett']})" if d.get("lac_dett") else ""))
    if d.get("ultima_visita"):
        sv.append("ultima visita oculistica: " + d["ultima_visita"])
    if sv:
        righe.append("Storia visiva: " + "; ".join(sv))
    if not righe:
        return ""
    return "### Anamnesi (sintesi)\n" + "\n".join(righe)


# ── UI ──────────────────────────────────────────────────────────────────
def render_anamnesi_visiva(conn, paz_id: int) -> None:
    st.subheader("👁️ Anamnesi visiva / optometrica")

    try:
        _ensure_table(conn)
    except Exception as e:
        st.error(f"Impossibile preparare la tabella: {e}")
        return

    d = _carica(conn, paz_id)
    if d:
        st.caption("Scheda già presente: i campi sono precompilati, modifica e risalva.")

    with st.form(f"anam_vis_{paz_id}"):
        # 1. Motivo / sintomi
        st.markdown("**1. Motivo della visita e sintomi**")
        motivo = st.text_input("Motivo della visita", value=d.get("motivo", ""))
        sintomi = st.multiselect("Sintomi visivi riferiti", SINTOMI,
                                 default=[s for s in d.get("sintomi", []) if s in SINTOMI])
        sintomi_altro = st.text_area("Altri sintomi / note", value=d.get("sintomi_altro", ""), height=70)

        # 2. Storia visiva
        st.markdown("**2. Storia visiva**")
        c1, c2 = st.columns(2)
        with c1:
            occhiali = st.radio("Porta occhiali?", ["No", "Sì"],
                                index=1 if d.get("occhiali") == "Sì" else 0, horizontal=True)
            occhiali_dett = st.text_input("Da quando / tipo occhiali", value=d.get("occhiali_dett", ""))
        with c2:
            lac = st.radio("Lenti a contatto?", ["No", "Sì"],
                           index=1 if d.get("lac") == "Sì" else 0, horizontal=True)
            lac_dett = st.text_input("Tipo lenti a contatto", value=d.get("lac_dett", ""))
        ultima_visita = st.text_input("Ultima visita oculistica (data/anno)", value=d.get("ultima_visita", ""))
        correzioni = st.text_area("Correzioni precedenti", value=d.get("correzioni", ""), height=70)

        # 3. Patologie oculari
        st.markdown("**3. Patologie oculari**")
        pat_personali = st.text_area("Patologie oculari personali (ambliopia, strabismo, glaucoma…)",
                                     value=d.get("pat_personali", ""), height=70)
        pat_familiari = st.text_area("Familiarità (patologie oculari in famiglia)",
                                     value=d.get("pat_familiari", ""), height=70)

        # 4. Interventi / traumi
        st.markdown("**4. Interventi e traumi oculari**")
        interventi = st.text_area("Interventi o traumi oculari", value=d.get("interventi", ""), height=70)

        # 5. Storia medica generale
        st.markdown("**5. Storia medica generale**")
        patologie_med = st.multiselect("Condizioni mediche", PATOLOGIE_MED,
                                       default=[p for p in d.get("patologie_med", []) if p in PATOLOGIE_MED])
        farmaci = st.text_input("Farmaci in uso", value=d.get("farmaci", ""))
        note_med = st.text_area("Altre note mediche / allergie", value=d.get("note_med", ""), height=70)

        # 6. Abitudini visive
        st.markdown("**6. Abitudini visive**")
        c3, c4 = st.columns(2)
        with c3:
            ore_schermo = st.number_input("Ore/giorno a schermo o lettura", min_value=0, max_value=24,
                                          value=int(d.get("ore_schermo", 0) or 0), step=1)
        with c4:
            sport = st.text_input("Attività sportiva", value=d.get("sport", ""))
        guida = st.checkbox("Guida abitualmente", value=bool(d.get("guida", False)))

        # 7. Note libere
        st.markdown("**7. Note libere**")
        note = st.text_area("Note", value=d.get("note", ""), height=90)

        salva = st.form_submit_button("💾 Salva anamnesi visiva", use_container_width=True)

    if salva:
        dati = {
            "motivo": motivo, "sintomi": sintomi, "sintomi_altro": sintomi_altro,
            "occhiali": occhiali, "occhiali_dett": occhiali_dett,
            "lac": lac, "lac_dett": lac_dett,
            "ultima_visita": ultima_visita, "correzioni": correzioni,
            "pat_personali": pat_personali, "pat_familiari": pat_familiari,
            "interventi": interventi,
            "patologie_med": patologie_med, "farmaci": farmaci, "note_med": note_med,
            "ore_schermo": int(ore_schermo), "sport": sport, "guida": bool(guida),
            "note": note,
        }
        _salva(conn, paz_id, dati)
