# -*- coding: utf-8 -*-
"""Oculistica — importato da Vision Manager come modulo indipendente.
Tabella propria (oculistica_visite): nessuna sovrapposizione con
valutazioni_visive (PNEV Visiva)."""
from __future__ import annotations
import datetime
import streamlit as st

AV_OPTIONS = [
    "NV - non vedente", "PL - percezione luce", "ML/HM - moto mano",
    "CF 30 cm", "CF 50 cm", "CF 1 m",
    "1/50", "1/20", "1/10", "2/10", "3/10", "4/10", "5/10", "6/10", "7/10",
    "8/10", "9/10", "10/10", "12/10", "14/10", "16/10",
]


def _av_select(label, current, key):
    opts = AV_OPTIONS.copy()
    if current and current not in opts:
        opts = [current] + opts
    else:
        opts = [""] + opts
    idx = opts.index(current) if current in opts else 0
    return st.selectbox(label, opts, index=idx, key=key)


def _cherato_mm_to_D(r_mm):
    return 337.5 / r_mm if r_mm else 0.0


def _cherato_D_to_mm(D):
    return 337.5 / D if D else 0.0


def _ensure_table(conn):
    cur = conn.cursor()
    cur.execute("""
        CREATE TABLE IF NOT EXISTS oculistica_visite (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            paziente_id BIGINT NOT NULL REFERENCES pazienti(id) ON DELETE CASCADE,
            data_visita DATE,
            tipo_visita TEXT,
            professionista TEXT,
            ac_nat_od TEXT, ac_nat_os TEXT, ac_nat_oo TEXT,
            ac_cor_od TEXT, ac_cor_os TEXT, ac_cor_oo TEXT,
            sf_ogg_od REAL, cil_ogg_od REAL, ax_ogg_od INT,
            sf_ogg_os REAL, cil_ogg_os REAL, ax_ogg_os INT,
            sf_sogg_od REAL, cil_sogg_od REAL, ax_sogg_od INT,
            sf_sogg_os REAL, cil_sogg_os REAL, ax_sogg_os INT,
            k1_od_mm REAL, k1_od_d REAL, k2_od_mm REAL, k2_od_d REAL,
            k1_os_mm REAL, k1_os_d REAL, k2_os_mm REAL, k2_os_d REAL,
            tono_od REAL, tono_os REAL,
            motilita TEXT, cover_test TEXT, stereopsi TEXT, ppc_cm REAL,
            ishihara TEXT, pachim_od REAL, pachim_os REAL,
            fondo TEXT, campo_visivo TEXT, oct TEXT, topo TEXT,
            cornea TEXT, camera_ant TEXT, cristallino TEXT,
            congiuntiva TEXT, iride_pupilla TEXT, vitreo TEXT,
            costo NUMERIC(10,2) DEFAULT 0, pagato BIGINT DEFAULT 0,
            note TEXT,
            creato_il TIMESTAMP DEFAULT now()
        )
    """)
    conn.commit()


def _salva(conn, paz_id, d):
    cur = conn.cursor()
    cols = list(d.keys())
    ph = ",".join(["%s"] * len(cols))
    cur.execute(
        f"INSERT INTO oculistica_visite (paziente_id,{','.join(cols)}) VALUES (%s,{ph})",
        [paz_id] + list(d.values()))
    conn.commit()


def _storico(conn, paz_id):
    cur = conn.cursor()
    cur.execute("""SELECT id, data_visita, tipo_visita, professionista, ac_cor_od, ac_cor_os
                   FROM oculistica_visite WHERE paziente_id=%s ORDER BY data_visita DESC, id DESC""",
                (paz_id,))
    return cur.fetchall()


def render_oculistica(conn, paz_id: int, paziente: dict = None) -> None:
    st.subheader("👁️ Oculistica")
    try:
        _ensure_table(conn)
    except Exception as e:
        st.error(f"Impossibile preparare la tabella: {e}")
        return

    rows = _storico(conn, paz_id)
    if rows:
        st.markdown("#### Storico visite")
        for r in rows:
            rid, data_v, tipo, prof, od, os_ = (r.get(k) if hasattr(r, "get") else r[i]
                                                 for i, k in enumerate(["id","data_visita","tipo_visita","professionista","ac_cor_od","ac_cor_os"]))
            st.caption(f"📅 {data_v or '—'} · {tipo or 'Visita'} · {prof or ''} · OD {od or '—'} / OS {os_ or '—'}")
        st.markdown("---")

    with st.form(f"ocul_nuova_{paz_id}"):
        st.markdown("**Nuova visita oculistica**")
        c1, c2, c3 = st.columns(3)
        data_v = c1.date_input("Data visita", datetime.date.today())
        tipo = c2.text_input("Tipo visita", "Controllo")
        prof = c3.text_input("Professionista", "")

        st.markdown("**Acuità visiva naturale**")
        c1, c2, c3 = st.columns(3)
        ac_nat_od = _av_select("OD naturale", "", "ocul_nat_od")
        ac_nat_os = _av_select("OS naturale", "", "ocul_nat_os")
        ac_nat_oo = _av_select("OO naturale", "", "ocul_nat_oo")

        st.markdown("**Acuità visiva corretta**")
        ac_cor_od = _av_select("OD corretta", "", "ocul_cor_od")
        ac_cor_os = _av_select("OS corretta", "", "ocul_cor_os")
        ac_cor_oo = _av_select("OO corretta", "", "ocul_cor_oo")

        st.markdown("**Refrazione oggettiva (SF / CIL / AX)**")
        c1, c2, c3 = st.columns(3)
        sf_ogg_od = c1.number_input("OD SF ogg. (D)", -30.0, 30.0, 0.0, 0.25, key="ocul_sf_ogg_od")
        cil_ogg_od = c2.number_input("OD CIL ogg. (D)", -10.0, 10.0, 0.0, 0.25, key="ocul_cil_ogg_od")
        ax_ogg_od = c3.number_input("OD AX ogg. (°)", 0, 180, 0, 1, key="ocul_ax_ogg_od")
        c4, c5, c6 = st.columns(3)
        sf_ogg_os = c4.number_input("OS SF ogg. (D)", -30.0, 30.0, 0.0, 0.25, key="ocul_sf_ogg_os")
        cil_ogg_os = c5.number_input("OS CIL ogg. (D)", -10.0, 10.0, 0.0, 0.25, key="ocul_cil_ogg_os")
        ax_ogg_os = c6.number_input("OS AX ogg. (°)", 0, 180, 0, 1, key="ocul_ax_ogg_os")

        st.markdown("**Refrazione soggettiva (SF / CIL / AX)**")
        c1, c2, c3 = st.columns(3)
        sf_sogg_od = c1.number_input("OD SF sogg. (D)", -30.0, 30.0, 0.0, 0.25, key="ocul_sf_sogg_od")
        cil_sogg_od = c2.number_input("OD CIL sogg. (D)", -10.0, 10.0, 0.0, 0.25, key="ocul_cil_sogg_od")
        ax_sogg_od = c3.number_input("OD AX sogg. (°)", 0, 180, 0, 1, key="ocul_ax_sogg_od")
        c4, c5, c6 = st.columns(3)
        sf_sogg_os = c4.number_input("OS SF sogg. (D)", -30.0, 30.0, 0.0, 0.25, key="ocul_sf_sogg_os")
        cil_sogg_os = c5.number_input("OS CIL sogg. (D)", -10.0, 10.0, 0.0, 0.25, key="ocul_cil_sogg_os")
        ax_sogg_os = c6.number_input("OS AX sogg. (°)", 0, 180, 0, 1, key="ocul_ax_sogg_os")

        st.markdown("**Cheratometria**")
        c1, c2, c3, c4 = st.columns(4)
        k1_od_mm = c1.number_input("OD K1 (mm)", 6.0, 9.5, 7.80, 0.01, key="ocul_k1_od_mm")
        k1_od_d = c2.number_input("OD K1 (D)", 35.0, 50.0, 43.0, 0.25, key="ocul_k1_od_d")
        k2_od_mm = c3.number_input("OD K2 (mm)", 6.0, 9.5, 7.80, 0.01, key="ocul_k2_od_mm")
        k2_od_d = c4.number_input("OD K2 (D)", 35.0, 50.0, 43.0, 0.25, key="ocul_k2_od_d")
        c1, c2, c3, c4 = st.columns(4)
        k1_os_mm = c1.number_input("OS K1 (mm)", 6.0, 9.5, 7.80, 0.01, key="ocul_k1_os_mm")
        k1_os_d = c2.number_input("OS K1 (D)", 35.0, 50.0, 43.0, 0.25, key="ocul_k1_os_d")
        k2_os_mm = c3.number_input("OS K2 (mm)", 6.0, 9.5, 7.80, 0.01, key="ocul_k2_os_mm")
        k2_os_d = c4.number_input("OS K2 (D)", 35.0, 50.0, 43.0, 0.25, key="ocul_k2_os_d")

        st.markdown("**Tonometria**")
        c1, c2 = st.columns(2)
        tono_od = c1.number_input("OD (mmHg)", 0.0, 60.0, 15.0, 0.5, key="ocul_tono_od")
        tono_os = c2.number_input("OS (mmHg)", 0.0, 60.0, 15.0, 0.5, key="ocul_tono_os")

        st.markdown("**Motilità, cover test, stereopsi, PPC**")
        motilita = st.text_input("Motilità oculare", "", key="ocul_motilita")
        cover_test = st.text_input("Cover test", "", key="ocul_cover")
        stereopsi = st.text_input("Stereopsi", "", key="ocul_stereo")
        ppc_cm = st.number_input("PPC (cm)", 0.0, 50.0, 10.0, 0.5, key="ocul_ppc")

        st.markdown("**Colori e pachimetria**")
        ishihara = st.text_input("Ishihara (esito)", "", key="ocul_ishihara")
        c1, c2 = st.columns(2)
        pachim_od = c1.number_input("Pachimetria OD (µm)", 400.0, 700.0, 540.0, 1.0, key="ocul_pachim_od")
        pachim_os = c2.number_input("Pachimetria OS (µm)", 400.0, 700.0, 540.0, 1.0, key="ocul_pachim_os")

        st.markdown("**Esami strutturali/funzionali**")
        fondo = st.text_area("Fondo oculare", "", height=68, key="ocul_fondo")
        campo_visivo = st.text_area("Campo visivo", "", height=68, key="ocul_campo")
        oct_txt = st.text_area("OCT", "", height=68, key="ocul_oct")
        topo = st.text_area("Topografia corneale", "", height=68, key="ocul_topo")

        st.markdown("**Esame obiettivo**")
        cornea = st.text_area("Cornea", "", height=60, key="ocul_cornea")
        camera_ant = st.text_area("Camera anteriore", "", height=60, key="ocul_camera")
        cristallino = st.text_area("Cristallino", "", height=60, key="ocul_cristallino")
        congiuntiva = st.text_area("Congiuntiva / Sclera", "", height=60, key="ocul_congiuntiva")
        iride_pupilla = st.text_area("Iride / Pupilla", "", height=60, key="ocul_iride")
        vitreo = st.text_area("Vitreo", "", height=60, key="ocul_vitreo")

        c1, c2 = st.columns(2)
        costo = c1.number_input("Costo visita €", min_value=0.0, step=5.0, value=0.0, key="ocul_costo")
        pagato = c2.checkbox("Pagato", value=False, key="ocul_pagato")
        note = st.text_area("Note cliniche", "", height=70, key="ocul_note")

        salva = st.form_submit_button("💾 Salva visita oculistica", type="primary", use_container_width=True)

    if salva:
        d = dict(
            data_visita=data_v.isoformat(), tipo_visita=tipo, professionista=prof,
            ac_nat_od=ac_nat_od, ac_nat_os=ac_nat_os, ac_nat_oo=ac_nat_oo,
            ac_cor_od=ac_cor_od, ac_cor_os=ac_cor_os, ac_cor_oo=ac_cor_oo,
            sf_ogg_od=sf_ogg_od, cil_ogg_od=cil_ogg_od, ax_ogg_od=int(ax_ogg_od),
            sf_ogg_os=sf_ogg_os, cil_ogg_os=cil_ogg_os, ax_ogg_os=int(ax_ogg_os),
            sf_sogg_od=sf_sogg_od, cil_sogg_od=cil_sogg_od, ax_sogg_od=int(ax_sogg_od),
            sf_sogg_os=sf_sogg_os, cil_sogg_os=cil_sogg_os, ax_sogg_os=int(ax_sogg_os),
            k1_od_mm=k1_od_mm, k1_od_d=k1_od_d, k2_od_mm=k2_od_mm, k2_od_d=k2_od_d,
            k1_os_mm=k1_os_mm, k1_os_d=k1_os_d, k2_os_mm=k2_os_mm, k2_os_d=k2_os_d,
            tono_od=tono_od, tono_os=tono_os,
            motilita=motilita, cover_test=cover_test, stereopsi=stereopsi, ppc_cm=ppc_cm,
            ishihara=ishihara, pachim_od=pachim_od, pachim_os=pachim_os,
            fondo=fondo, campo_visivo=campo_visivo, oct=oct_txt, topo=topo,
            cornea=cornea, camera_ant=camera_ant, cristallino=cristallino,
            congiuntiva=congiuntiva, iride_pupilla=iride_pupilla, vitreo=vitreo,
            costo=float(costo), pagato=1 if pagato else 0, note=note,
        )
        try:
            _salva(conn, paz_id, d)
            st.success("Visita oculistica salvata.")
            st.rerun()
        except Exception as e:
            st.error(f"Errore salvataggio: {e}")

    with st.expander("🧮 Cheratometria rapida (mm ⇄ diottrie)"):
        modo = st.radio("Conversione", ["mm → diottrie", "diottrie → mm"], key="ocul_cherato_modo", horizontal=True)
        if modo == "mm → diottrie":
            r = st.number_input("Raggio corneale (mm)", 6.0, 9.5, 7.80, 0.01, key="ocul_cherato_r")
            if st.button("Calcola potere (D)", key="ocul_btn_cherato1"):
                st.success(f"Potere corneale ≈ {_cherato_mm_to_D(r):.2f} D")
        else:
            D = st.number_input("Potere corneale (D)", 35.0, 50.0, 43.0, 0.25, key="ocul_cherato_D")
            if st.button("Calcola raggio (mm)", key="ocul_btn_cherato2"):
                st.success(f"Raggio corneale ≈ {_cherato_D_to_mm(D):.2f} mm")
