# -*- coding: utf-8 -*-
"""Consenso screening scolastico — raccolta digitale nel gestionale,
stessa struttura del modulo cartaceo da portare poi su pnev.it."""
from __future__ import annotations
import datetime
import streamlit as st

SCREENING_OPTS = ["Visivo", "Uditivo", "Riflessi primitivi (INPP)", "Apprendimenti", "Miofunzionale"]


def _ensure_table(conn):
    try:
        conn.rollback()
    except Exception:
        pass
    cur = conn.cursor()
    cur.execute("""
        CREATE TABLE IF NOT EXISTS screening_consensi (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            cognome_bambino TEXT, nome_bambino TEXT, data_nascita_bambino DATE,
            scuola TEXT, classe TEXT, comune TEXT,
            cognome_genitore TEXT, nome_genitore TEXT, telefono TEXT, email TEXT,
            rapporto TEXT,
            screening_scelti TEXT,
            consenso_trattamento BOOLEAN DEFAULT FALSE,
            consenso_contatto BOOLEAN DEFAULT FALSE,
            data_firma DATE,
            note TEXT,
            creato_il TIMESTAMP DEFAULT now()
        )
    """)
    conn.commit()


def _salva(conn, d):
    cur = conn.cursor()
    cur.execute("""
        INSERT INTO screening_consensi
        (cognome_bambino, nome_bambino, data_nascita_bambino, scuola, classe, comune,
         cognome_genitore, nome_genitore, telefono, email, rapporto,
         screening_scelti, consenso_trattamento, consenso_contatto, data_firma, note)
        VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
    """, (
        d["cognome_b"], d["nome_b"], d["dn_b"], d["scuola"], d["classe"], d["comune"],
        d["cognome_g"], d["nome_g"], d["tel"], d["email"], d["rapporto"],
        ", ".join(d["screening"]), d["cons_tratt"], d["cons_contatto"], d["data_firma"], d["note"],
    ))
    conn.commit()


def _storico(conn, limit=200):
    cur = conn.cursor()
    cur.execute("""SELECT id, cognome_bambino, nome_bambino, scuola, classe, screening_scelti, data_firma
                   FROM screening_consensi ORDER BY creato_il DESC LIMIT %s""", (limit,))
    return cur.fetchall()


def render_screening_scolastico(conn) -> None:
    st.subheader("📋 Consenso screening scolastico")
    st.caption("Visivo · Uditivo · Riflessi primitivi (INPP) · Apprendimenti · Miofunzionale — "
              "stessa struttura del modulo cartaceo, per raccolta rapida in loco o da riportare qui dopo.")
    try:
        _ensure_table(conn)
    except Exception as e:
        st.error(f"Impossibile preparare la tabella: {e}")
        return

    with st.form("screening_consenso_nuovo"):
        st.markdown("**Dati del bambino/a**")
        c1, c2, c3 = st.columns(3)
        cognome_b = c1.text_input("Cognome")
        nome_b = c2.text_input("Nome")
        dn_b = c3.date_input("Data di nascita", datetime.date(2015, 1, 1),
                             min_value=datetime.date(2005, 1, 1), max_value=datetime.date.today())
        c4, c5, c6 = st.columns(3)
        scuola = c4.text_input("Scuola")
        classe = c5.text_input("Classe")
        comune = c6.text_input("Comune")

        st.markdown("**Dati del genitore/tutore**")
        c1, c2 = st.columns(2)
        cognome_g = c1.text_input("Cognome genitore")
        nome_g = c2.text_input("Nome genitore")
        c3, c4 = st.columns(2)
        tel = c3.text_input("Telefono")
        email = c4.text_input("Email")
        rapporto = st.selectbox("Rapporto con il minore", ["Genitore", "Tutore legale"])

        st.markdown("**Screening a cui si presta consenso**")
        screening = st.multiselect("Seleziona uno o più screening", SCREENING_OPTS)

        st.markdown("**Consensi**")
        cons_tratt = st.checkbox("Acconsento al trattamento dei dati per le finalità dello screening")
        cons_contatto = st.checkbox("Acconsento a essere ricontattato/a per l'esito e un eventuale approfondimento")

        c1, c2 = st.columns(2)
        data_firma = c1.date_input("Data firma", datetime.date.today())
        note = c2.text_input("Note (facoltative)")

        salva = st.form_submit_button("💾 Salva consenso", type="primary", use_container_width=True)

    if salva:
        if not cognome_b.strip() or not nome_b.strip():
            st.error("Cognome e nome del bambino sono obbligatori.")
        elif not screening:
            st.error("Seleziona almeno uno screening.")
        elif not cons_tratt:
            st.error("Il consenso al trattamento dati è obbligatorio.")
        else:
            _salva(conn, dict(
                cognome_b=cognome_b.strip().upper(), nome_b=nome_b.strip().title(),
                dn_b=dn_b.isoformat(), scuola=scuola.strip(), classe=classe.strip(), comune=comune.strip(),
                cognome_g=cognome_g.strip().upper(), nome_g=nome_g.strip().title(),
                tel=tel.strip(), email=email.strip().lower(), rapporto=rapporto,
                screening=screening, cons_tratt=cons_tratt, cons_contatto=cons_contatto,
                data_firma=data_firma.isoformat(), note=note.strip(),
            ))
            st.success(f"Consenso salvato per {cognome_b} {nome_b}.")
            st.rerun()

    st.markdown("---")
    st.markdown("#### Storico consensi raccolti")
    rows = _storico(conn)
    if not rows:
        st.caption("Nessun consenso ancora registrato.")
    else:
        for r in rows:
            rid, cog, nom, scuola_r, classe_r, scr, data_f = (
                r.get(k) if hasattr(r, "get") else r[i]
                for i, k in enumerate(["id","cognome_bambino","nome_bambino","scuola","classe","screening_scelti","data_firma"]))
            st.caption(f"👤 {cog} {nom} · {scuola_r or '—'} {classe_r or ''} · {scr or '—'} · firmato {data_f or '—'}")
