import os
import sqlite3


def _env(key: str, default: str = "") -> str:
    v = os.getenv(key)
    return v if v not in (None, "") else default


def get_conn():
    """Restituisce una nuova connessione DB ogni volta."""
    db_url = _env("DATABASE_URL", "")
    if db_url:
        import psycopg2
        from psycopg2.extras import RealDictCursor
        return psycopg2.connect(
            db_url,
            cursor_factory=RealDictCursor,
            connect_timeout=8,
            keepalives=1,
            keepalives_idle=30,
            keepalives_interval=10,
            keepalives_count=5,
        )
    return sqlite3.connect("vision_manager.db", check_same_thread=False)


def _is_pg(conn) -> bool:
    return conn.__class__.__module__.startswith("psycopg2")


def _add_col_if_missing(conn, table: str, col: str, ddl: str):
    cur = conn.cursor()
    try:
        if _is_pg(conn):
            cur.execute(
                """
                SELECT 1 FROM information_schema.columns
                WHERE table_schema='public' AND table_name=%s AND column_name=%s
                """,
                (table, col),
            )
            if cur.fetchone() is None:
                cur.execute(f"ALTER TABLE {table} ADD COLUMN {ddl}")
                conn.commit()
        else:
            cur.execute(f"PRAGMA table_info({table})")
            cols = [r[1] for r in cur.fetchall()]
            if col not in cols:
                cur.execute(f"ALTER TABLE {table} ADD COLUMN {ddl}")
                conn.commit()
    finally:
        try:
            cur.close()
        except Exception:
            pass


def init_db(conn):
    if conn is None:
        raise RuntimeError("init_db(conn): conn è None. Verifica get_conn() e DATABASE_URL.")
    if not hasattr(conn, "cursor"):
        raise TypeError(f"init_db(conn): oggetto non valido ({type(conn)}), manca .cursor().")

    cur = conn.cursor()
    try:
        if _is_pg(conn):
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS visite_visive (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    paziente_id BIGINT NOT NULL REFERENCES pazienti(id) ON DELETE CASCADE,
                    data_visita TEXT,
                    dati_json JSONB,
                    pdf_bytes BYTEA,
                    is_deleted INTEGER DEFAULT 0,
                    deleted_at TIMESTAMP NULL
                );
                """
            )

            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS prescrizioni_occhiali (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    paziente_id BIGINT NOT NULL REFERENCES pazienti(id) ON DELETE CASCADE,
                    data_prescrizione TEXT,
                    formato TEXT,
                    dati_json JSONB,
                    pdf_bytes BYTEA
                );
                """
            )

            _add_col_if_missing(conn, "visite_visive", "is_deleted", "is_deleted INTEGER DEFAULT 0")
            _add_col_if_missing(conn, "visite_visive", "deleted_at", "deleted_at TIMESTAMP NULL")
            conn.commit()
            return

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS Pazienti (
                ID INTEGER PRIMARY KEY AUTOINCREMENT,
                Cognome TEXT,
                Nome TEXT,
                Data_Nascita TEXT,
                Note TEXT
            );
            """
        )

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS visite_visive (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                paziente_id INTEGER,
                data_visita TEXT,
                dati_json TEXT,
                pdf_bytes BLOB,
                is_deleted INTEGER DEFAULT 0,
                deleted_at TEXT
            );
            """
        )

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS prescrizioni_occhiali (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                paziente_id INTEGER,
                data_prescrizione TEXT,
                formato TEXT,
                dati_json TEXT,
                pdf_bytes BLOB
            );
            """
        )

        conn.commit()
    except Exception:
        try:
            conn.rollback()
        except Exception:
            pass
        raise
    finally:
        try:
            cur.close()
        except Exception:
            pass
