import os
import sqlite3

def _env(key: str, default: str = "") -> str:
    v = os.getenv(key)
    return v if v not in (None, "") else default


def get_conn():
    """Return a DB connection (Postgres if DATABASE_URL set, else local SQLite)."""
    db_url = _env("DATABASE_URL", "")
    if db_url:
        import psycopg2
        from psycopg2.extras import RealDictCursor
        # RealDictCursor -> row as dict (comodo nel Vision Manager)
        return psycopg2.connect(db_url, cursor_factory=RealDictCursor)
    return sqlite3.connect("vision_manager.db", check_same_thread=False)


def _is_pg(conn) -> bool:
    return conn.__class__.__module__.startswith("psycopg2")


def _add_col_if_missing(conn, table: str, col: str, ddl: str):
    cur = conn.cursor()
    try:
        if _is_pg(conn):
            cur.execute(
                """
                SELECT 1 FROM information_schema.columns
                WHERE table_schema='public' AND table_name=%s AND column_name=%s
                """,
                (table, col),
            )
            if cur.fetchone() is None:
                cur.execute(f"ALTER TABLE {table} ADD COLUMN {ddl}")
                conn.commit()
        else:
            cur.execute(f"PRAGMA table_info({table})")
            cols = [r[1] for r in cur.fetchall()]
            if col not in cols:
                cur.execute(f"ALTER TABLE {table} ADD COLUMN {ddl}")
                conn.commit()
    finally:
        try:
            cur.close()
        except Exception:
            pass


def init_db(conn):
    """Initialize Vision Manager schema (visite_visive + prescrizioni_occhiali).

    IMPORTANT:
    - Non crea la tabella pazienti su Postgres: usa quella centrale del gestionale (public.pazienti).
    - Su SQLite locale crea una tabella Pazienti legacy per test/offline.
    """
    if conn is None:
        raise RuntimeError("init_db(conn): conn è None. Verifica get_conn() e DATABASE_URL.")
    if callable(conn):
        conn = conn()
    if not hasattr(conn, "cursor"):
        raise TypeError(f"init_db(conn): oggetto non valido ({type(conn)}), manca .cursor().")

    cur = conn.cursor()

    if _is_pg(conn):
        # visite_visive
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS visite_visive (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                paziente_id BIGINT NOT NULL REFERENCES pazienti(id) ON DELETE CASCADE,
                data_visita TEXT,
                dati_json JSONB,
                pdf_bytes BYTEA,
                is_deleted INTEGER DEFAULT 0,
                deleted_at TEXT
            );
            """
        )

        # prescrizioni_occhiali
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS prescrizioni_occhiali (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                paziente_id BIGINT NOT NULL REFERENCES pazienti(id) ON DELETE CASCADE,
                data_prescrizione TEXT,
                formato TEXT,
                dati_json JSONB,
                pdf_bytes BYTEA
            );
            """
        )

        conn.commit()
        return

    # SQLite (locale)
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS Pazienti (
            ID INTEGER PRIMARY KEY AUTOINCREMENT,
            Cognome TEXT,
            Nome TEXT,
            Data_Nascita TEXT,
            Note TEXT
        );
        """
    )

    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS visite_visive (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            paziente_id INTEGER,
            data_visita TEXT,
            dati_json TEXT,
            pdf_bytes BLOB,
            is_deleted INTEGER DEFAULT 0,
            deleted_at TEXT
        );
        """
    )

    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS prescrizioni_occhiali (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            paziente_id INTEGER,
            data_prescrizione TEXT,
            formato TEXT,
            dati_json TEXT,
            pdf_bytes BLOB
        );
        """
    )

    conn.commit()
