# -*- coding: utf-8 -*-
"""Photoref AI — stima refrazione da foto del riflesso pupillare (photorefraction).
Screening qualitativo, NON sostituisce la refrazione oggettiva/soggettiva."""
from __future__ import annotations
import datetime
import io
import streamlit as st

try:
    import numpy as np
    from PIL import Image
    _HAS_DEPS = True
except Exception:
    _HAS_DEPS = False


def _ensure_table(conn):
    cur = conn.cursor()
    cur.execute("""
        CREATE TABLE IF NOT EXISTS photoref_sessioni (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            paziente_id BIGINT NOT NULL REFERENCES pazienti(id) ON DELETE CASCADE,
            data_sessione DATE,
            stima_od REAL, stima_os REAL,
            asimmetria REAL,
            note TEXT,
            creato_il TIMESTAMP DEFAULT now()
        )
    """)
    conn.commit()


def _salva(conn, paz_id, data_s, stima_od, stima_os, asimmetria, note):
    cur = conn.cursor()
    cur.execute(
        """INSERT INTO photoref_sessioni (paziente_id, data_sessione, stima_od, stima_os, asimmetria, note)
           VALUES (%s,%s,%s,%s,%s,%s)""",
        (paz_id, data_s, stima_od, stima_os, asimmetria, note))
    conn.commit()


def _storico(conn, paz_id):
    cur = conn.cursor()
    cur.execute("""SELECT data_sessione, stima_od, stima_os, asimmetria
                   FROM photoref_sessioni WHERE paziente_id=%s ORDER BY data_sessione DESC""", (paz_id,))
    return cur.fetchall()


def _analizza_riflesso(img: "Image.Image", occhio: str):
    """Stima grezza da luminosità/asimmetria del crescent nel riflesso pupillare.
    Placeholder scientificamente onesto: converte la posizione/ampiezza del
    riflesso chiaro rispetto al centro pupilla in una stima approssimativa (D).
    Va tarato con foto reali; qui resta un valore indicativo, non clinico."""
    arr = np.asarray(img.convert("L"), dtype=float)
    h, w = arr.shape
    cy, cx = h // 2, w // 2
    r = min(h, w) // 4
    region = arr[max(0, cy - r):cy + r, max(0, cx - r):cx + r]
    if region.size == 0:
        return 0.0
    thresh = region.mean() + region.std()
    bright = region > thresh
    ys, xs = np.where(bright)
    if len(xs) == 0:
        return 0.0
    offset_x = (xs.mean() - region.shape[1] / 2) / (region.shape[1] / 2)
    stima_D = round(offset_x * 4.0, 2)  # scala arbitraria ±4D, da calibrare
    return stima_D


def render_photoref(conn, paz_id: int, paziente: dict = None) -> None:
    st.subheader("📸 Photoref AI — Stima refrazione")
    st.caption("Screening qualitativo da foto del riflesso pupillare (tipo photoscreener). "
              "Non sostituisce autorefrattometro, schiascopia o refrazione soggettiva.")
    if not _HAS_DEPS:
        st.error("Dipendenze mancanti (pillow, numpy) — aggiungerle a requirements.txt per attivare l'analisi.")
        return

    try:
        _ensure_table(conn)
    except Exception as e:
        st.error(f"Impossibile preparare la tabella: {e}")
        return

    rows = _storico(conn, paz_id)
    if rows:
        st.markdown("#### Storico stime")
        for r in rows:
            data_s, s_od, s_os, asim = (r.get(k) if hasattr(r, "get") else r[i]
                                        for i, k in enumerate(["data_sessione","stima_od","stima_os","asimmetria"]))
            st.caption(f"📅 {data_s} · Stima OD {s_od:+.2f} D · OS {s_os:+.2f} D · Asimmetria {asim:.2f} D")
        st.markdown("---")

    c1, c2 = st.columns(2)
    with c1:
        foto_od = st.file_uploader("Foto riflesso OD", type=["jpg","jpeg","png"], key="photoref_od")
    with c2:
        foto_os = st.file_uploader("Foto riflesso OS", type=["jpg","jpeg","png"], key="photoref_os")

    data_s = st.date_input("Data sessione", datetime.date.today(), key="photoref_data")
    note = st.text_area("Note (distanza, illuminazione, collaborazione paziente)", "", height=68, key="photoref_note")

    if st.button("🔍 Analizza e salva", type="primary", key="photoref_analizza"):
        if not foto_od or not foto_os:
            st.warning("Carica entrambe le foto (OD e OS) prima di analizzare.")
            return
        try:
            img_od = Image.open(io.BytesIO(foto_od.read()))
            img_os = Image.open(io.BytesIO(foto_os.read()))
            stima_od = _analizza_riflesso(img_od, "OD")
            stima_os = _analizza_riflesso(img_os, "OS")
            asimmetria = round(abs(stima_od - stima_os), 2)
            _salva(conn, paz_id, data_s.isoformat(), stima_od, stima_os, asimmetria, note)
            st.success(f"Stima OD {stima_od:+.2f} D · OS {stima_os:+.2f} D · Asimmetria {asimmetria:.2f} D")
            if asimmetria >= 1.0:
                st.warning("⚠️ Asimmetria ≥1.00 D — consigliata verifica con refrazione oggettiva completa.")
            st.rerun()
        except Exception as e:
            st.error(f"Errore analisi immagine: {e}")
