# -*- coding: utf-8 -*-
"""Photoref AI — stima refrazione da foto del riflesso pupillare (photorefraction).
Screening qualitativo, NON sostituisce la refrazione oggettiva/soggettiva."""
from __future__ import annotations
import datetime
import hashlib, hmac, secrets as _sec
import io
import base64
import streamlit as st
import streamlit.components.v1 as components

try:
    import numpy as np
    from PIL import Image
    _HAS_DEPS = True
except Exception:
    _HAS_DEPS = False


def _token_secret():
    return str(st.secrets.get("privacy", {}).get("TOKEN_SECRET", "fallback_secret")).encode("utf-8")


def _ensure_link_table(conn):
    cur = conn.cursor()
    cur.execute("""
        CREATE TABLE IF NOT EXISTS photoref_link_token (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            paziente_id BIGINT NOT NULL REFERENCES pazienti(id) ON DELETE CASCADE,
            token_hash TEXT NOT NULL UNIQUE,
            created_at TIMESTAMP DEFAULT now(),
            expires_at TIMESTAMP,
            used_at TIMESTAMP
        )
    """)
    conn.commit()


def genera_link_cattura_mobile(conn, paziente_id: int, base_url: str, ttl_minutes: int = 30) -> str:
    """Crea un link mobile monouso valido ttl_minutes, senza login."""
    _ensure_link_table(conn)
    token = _sec.token_urlsafe(24)
    token_hash = hmac.new(_token_secret(), token.encode("utf-8"), hashlib.sha256).hexdigest()
    now = datetime.datetime.utcnow()
    exp = now + datetime.timedelta(minutes=ttl_minutes)
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO photoref_link_token (paziente_id, token_hash, created_at, expires_at) VALUES (%s,%s,%s,%s)",
        (paziente_id, token_hash, now.isoformat(), exp.isoformat()))
    conn.commit()
    return f"{base_url.rstrip('/')}/?photoref_token={token}"


def verifica_token_cattura(conn, token: str):
    """Ritorna paziente_id se il token è valido e non scaduto/usato, altrimenti None."""
    if not token:
        return None
    token_hash = hmac.new(_token_secret(), token.encode("utf-8"), hashlib.sha256).hexdigest()
    cur = conn.cursor()
    cur.execute("SELECT paziente_id, expires_at, used_at FROM photoref_link_token WHERE token_hash=%s", (token_hash,))
    row = cur.fetchone()
    if not row:
        return None
    pid, exp, used = (row.get("paziente_id"), row.get("expires_at"), row.get("used_at")) if hasattr(row, "get") else (row[0], row[1], row[2])
    if used:
        return None
    try:
        exp_dt = exp if isinstance(exp, datetime.datetime) else datetime.datetime.fromisoformat(str(exp))
        if datetime.datetime.utcnow() > exp_dt:
            return None
    except Exception:
        pass
    return pid


def marca_token_usato(conn, token: str):
    token_hash = hmac.new(_token_secret(), token.encode("utf-8"), hashlib.sha256).hexdigest()
    cur = conn.cursor()
    cur.execute("UPDATE photoref_link_token SET used_at=%s WHERE token_hash=%s",
                (datetime.datetime.utcnow().isoformat(), token_hash))
    conn.commit()


def _ensure_table(conn):
    cur = conn.cursor()
    cur.execute("""
        CREATE TABLE IF NOT EXISTS photoref_sessioni (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            paziente_id BIGINT NOT NULL REFERENCES pazienti(id) ON DELETE CASCADE,
            data_sessione DATE,
            stima_od REAL, stima_os REAL,
            asimmetria REAL,
            note TEXT,
            creato_il TIMESTAMP DEFAULT now()
        )
    """)
    conn.commit()


def _salva(conn, paz_id, data_s, stima_od, stima_os, asimmetria, note):
    cur = conn.cursor()
    cur.execute(
        """INSERT INTO photoref_sessioni (paziente_id, data_sessione, stima_od, stima_os, asimmetria, note)
           VALUES (%s,%s,%s,%s,%s,%s)""",
        (paz_id, data_s, stima_od, stima_os, asimmetria, note))
    conn.commit()


def _storico(conn, paz_id):
    cur = conn.cursor()
    cur.execute("""SELECT data_sessione, stima_od, stima_os, asimmetria
                   FROM photoref_sessioni WHERE paziente_id=%s ORDER BY data_sessione DESC""", (paz_id,))
    return cur.fetchall()


def _analizza_riflesso(img: "Image.Image", occhio: str):
    """Stima grezza da luminosità/asimmetria del crescent nel riflesso pupillare.
    Placeholder scientificamente onesto: converte la posizione/ampiezza del
    riflesso chiaro rispetto al centro pupilla in una stima approssimativa (D).
    Va tarato con foto reali; qui resta un valore indicativo, non clinico."""
    arr = np.asarray(img.convert("L"), dtype=float)
    h, w = arr.shape
    cy, cx = h // 2, w // 2
    r = min(h, w) // 4
    region = arr[max(0, cy - r):cy + r, max(0, cx - r):cx + r]
    if region.size == 0:
        return 0.0
    thresh = region.mean() + region.std()
    bright = region > thresh
    ys, xs = np.where(bright)
    if len(xs) == 0:
        return 0.0
    offset_x = (xs.mean() - region.shape[1] / 2) / (region.shape[1] / 2)
    stima_D = round(offset_x * 4.0, 2)  # scala arbitraria ±4D, da calibrare
    return stima_D


_CAPTURE_HTML = """
<div style="font-family:-apple-system,sans-serif;background:#0d1117;color:#e6edf3;padding:14px;border-radius:10px">
  <div style="display:flex;gap:8px;align-items:center;margin-bottom:10px">
    <span id="pr_step" style="font-weight:700">1/2 — Occhio destro (OD)</span>
    <span id="pr_dist" style="margin-left:auto;font-size:13px;color:#8b949e">Distanza: —</span>
  </div>
  <div style="position:relative;width:100%;max-width:420px;aspect-ratio:4/3;background:#000;border-radius:8px;overflow:hidden;margin:0 auto">
    <video id="pr_video" autoplay playsinline muted style="width:100%;height:100%;object-fit:cover"></video>
    <canvas id="pr_overlay" style="position:absolute;left:0;top:0;width:100%;height:100%"></canvas>
  </div>
  <canvas id="pr_shot" style="display:none"></canvas>
  <div style="display:flex;gap:10px;margin-top:12px;flex-wrap:wrap;justify-content:center">
    <button id="pr_torch" style="padding:10px 14px;border-radius:7px;border:none;background:#30363d;color:#fff;font-weight:600">🔦 Flash</button>
    <button id="pr_zoom_in" style="padding:10px 14px;border-radius:7px;border:none;background:#30363d;color:#fff;font-weight:600">🔍+ Zoom</button>
    <button id="pr_zoom_out" style="padding:10px 14px;border-radius:7px;border:none;background:#30363d;color:#fff;font-weight:600">🔍- Zoom</button>
    <button id="pr_capture" style="padding:10px 18px;border-radius:7px;border:none;background:#2ea44f;color:#fff;font-weight:700">📸 Scatta</button>
  </div>
  <div id="pr_msg" style="font-size:13px;color:#f0883e;margin-top:8px;text-align:center"></div>
  <div id="pr_preview" style="display:none;margin-top:12px;text-align:center">
    <img id="pr_img_od" style="max-width:140px;border-radius:6px;margin:4px" />
    <img id="pr_img_os" style="max-width:140px;border-radius:6px;margin:4px" />
  </div>
</div>
<script>
(function(){
  const video = document.getElementById('pr_video');
  const overlay = document.getElementById('pr_overlay');
  const octx = overlay.getContext('2d');
  const shot = document.getElementById('pr_shot');
  const msg = document.getElementById('pr_msg');
  const stepEl = document.getElementById('pr_step');
  let stream=null, track=null, zoomCap=null, zoomVal=1, torchOn=false, step=0;
  let shots=[null,null];

  function drawGuide(){
    octx.clearRect(0,0,overlay.width,overlay.height);
    octx.strokeStyle='#f0883e'; octx.lineWidth=3; octx.setLineDash([10,7]);
    octx.beginPath();
    octx.ellipse(overlay.width/2, overlay.height/2, overlay.width*0.18, overlay.height*0.28, 0, 0, 6.2832);
    octx.stroke();
  }

  async function start(){
    try{
      stream = await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment', width:{ideal:1280}, height:{ideal:960}}});
      video.srcObject = stream;
      await video.play();
      overlay.width = video.videoWidth||420; overlay.height = video.videoHeight||315;
      drawGuide();
      track = stream.getVideoTracks()[0];
      const caps = track.getCapabilities ? track.getCapabilities() : {};
      if (caps.zoom) zoomCap = caps.zoom;
      if (!caps.torch) document.getElementById('pr_torch').style.opacity='0.4';
      requestAnimationFrame(loop);
    }catch(e){
      msg.textContent = 'Impossibile avviare la fotocamera: ' + e.message + ' — consenti l\\'accesso e usa Chrome/Safari su HTTPS.';
    }
  }
  function loop(){ drawGuide(); requestAnimationFrame(loop); }

  document.getElementById('pr_torch').onclick = async ()=>{
    if(!track) return;
    torchOn = !torchOn;
    try{ await track.applyConstraints({advanced:[{torch:torchOn}]}); }
    catch(e){ msg.textContent='Flash non supportato su questo dispositivo.'; }
  };
  document.getElementById('pr_zoom_in').onclick = async ()=>{
    if(!track||!zoomCap) return;
    zoomVal = Math.min(zoomCap.max, zoomVal + (zoomCap.step||0.5));
    try{ await track.applyConstraints({advanced:[{zoom:zoomVal}]}); }catch(e){}
  };
  document.getElementById('pr_zoom_out').onclick = async ()=>{
    if(!track||!zoomCap) return;
    zoomVal = Math.max(zoomCap.min||1, zoomVal - (zoomCap.step||0.5));
    try{ await track.applyConstraints({advanced:[{zoom:zoomVal}]}); }catch(e){}
  };

  document.getElementById('pr_capture').onclick = ()=>{
    shot.width = video.videoWidth; shot.height = video.videoHeight;
    const sctx = shot.getContext('2d');
    sctx.drawImage(video, 0, 0);
    const cx = shot.width/2, cy = shot.height/2, rw = shot.width*0.20, rh = shot.height*0.30;
    const crop = document.createElement('canvas'); crop.width=rw*2; crop.height=rh*2;
    crop.getContext('2d').drawImage(shot, cx-rw, cy-rh, rw*2, rh*2, 0, 0, rw*2, rh*2);
    const dataUrl = crop.toDataURL('image/jpeg', 0.92);
    shots[step] = dataUrl;
    if (step===0){
      document.getElementById('pr_img_od').src = dataUrl;
      step = 1; stepEl.textContent = '2/2 — Occhio sinistro (OS)';
      msg.textContent = 'OD acquisito. Ora inquadra OS.';
    } else {
      document.getElementById('pr_img_os').src = dataUrl;
      document.getElementById('pr_preview').style.display='block';
      msg.style.color = '#7ee787';
      msg.textContent = 'Entrambe le foto acquisite. Invio in corso…';
      if(stream) stream.getTracks().forEach(t=>t.stop());
      const payload = JSON.stringify({od: shots[0], os: shots[1]});
      window.parent.postMessage({type:'photoref_capture', payload: payload}, '*');
    }
  };
  start();
})();
</script>
"""


def render_capture_mobile(conn, paz_id: int, token: str = None) -> None:
    """Pagina di cattura mobile guidata (flash, zoom, crop) — no login richiesto
    quando arrivata da link con photoref_token."""
    st.markdown("### 📸 Photoref AI — Cattura guidata")
    st.caption("Tieni il telefono a circa 40 cm dal viso, ambiente poco illuminato per attivare il riflesso pupillare.")
    b64 = base64.b64encode(_CAPTURE_HTML.encode("utf-8")).decode("ascii")
    iframe = (f'<iframe src="data:text/html;base64,{b64}" '
             f'allow="camera; fullscreen" '
             f'style="width:100%;height:640px;border:none;border-radius:10px"></iframe>')
    st.markdown(iframe, unsafe_allow_html=True)

    captured = st.query_params.get("pr_data", "")
    data_json = st.text_area("Incolla qui il risultato se l'invio automatico non parte", "", height=0,
                             key="pr_manual_fallback", label_visibility="collapsed") if False else None

    result = st.session_state.get("_photoref_capture_payload")
    if st.button("🔄 Ho scattato entrambe le foto — analizza ora", key="pr_confirm_capture"):
        st.info("Se le foto sono state acquisite dal riquadro sopra, usa il modulo standard 'Carica foto' per completare l'analisi (upload manuale) finché l'invio automatico via browser non è collegato al backend.")


def render_photoref(conn, paz_id: int, paziente: dict = None) -> None:
    st.subheader("📸 Photoref AI — Stima refrazione")
    st.caption("Screening qualitativo da foto del riflesso pupillare (tipo photoscreener). "
              "Non sostituisce autorefrattometro, schiascopia o refrazione soggettiva.")
    if not _HAS_DEPS:
        st.error("Dipendenze mancanti (pillow, numpy) — aggiungerle a requirements.txt per attivare l'analisi.")
        return

    try:
        _ensure_table(conn)
        _ensure_link_table(conn)
    except Exception as e:
        st.error(f"Impossibile preparare la tabella: {e}")
        return

    st.markdown("##### 📱 Genera link cattura mobile (guidata, con flash/zoom)")
    base_url = st.text_input("URL pubblico del gestionale", "https://theorganism.com", key="pr_base_url")
    ttl = st.number_input("Validità link (minuti)", 5, 180, 30, 5, key="pr_ttl")
    if st.button("🔗 Genera link", key="pr_gen_link"):
        url = genera_link_cattura_mobile(conn, paz_id, base_url, int(ttl))
        st.code(url, language="text")
        st.caption("Apri questo link sul telefono del paziente/operatore: guida flash+zoom+distanza, poi le foto tornano qui.")
    st.markdown("---")

    rows = _storico(conn, paz_id)
    if rows:
        st.markdown("#### Storico stime")
        for r in rows:
            data_s, s_od, s_os, asim = (r.get(k) if hasattr(r, "get") else r[i]
                                        for i, k in enumerate(["data_sessione","stima_od","stima_os","asimmetria"]))
            st.caption(f"📅 {data_s} · Stima OD {s_od:+.2f} D · OS {s_os:+.2f} D · Asimmetria {asim:.2f} D")
        st.markdown("---")

    st.markdown("#### Carica foto (o usa il link mobile sopra e poi carica qui il risultato)")
    c1, c2 = st.columns(2)
    with c1:
        foto_od = st.file_uploader("Foto riflesso OD", type=["jpg","jpeg","png"], key="photoref_od")
    with c2:
        foto_os = st.file_uploader("Foto riflesso OS", type=["jpg","jpeg","png"], key="photoref_os")

    data_s = st.date_input("Data sessione", datetime.date.today(), key="photoref_data")
    note = st.text_area("Note (distanza, illuminazione, collaborazione paziente)", "", height=68, key="photoref_note")

    if st.button("🔍 Analizza e salva", type="primary", key="photoref_analizza"):
        if not foto_od or not foto_os:
            st.warning("Carica entrambe le foto (OD e OS) prima di analizzare.")
            return
        try:
            img_od = Image.open(io.BytesIO(foto_od.read()))
            img_os = Image.open(io.BytesIO(foto_os.read()))
            stima_od = _analizza_riflesso(img_od, "OD")
            stima_os = _analizza_riflesso(img_os, "OS")
            asimmetria = round(abs(stima_od - stima_os), 2)
            _salva(conn, paz_id, data_s.isoformat(), stima_od, stima_os, asimmetria, note)
            st.success(f"Stima OD {stima_od:+.2f} D · OS {stima_os:+.2f} D · Asimmetria {asimmetria:.2f} D")
            if asimmetria >= 1.0:
                st.warning("⚠️ Asimmetria ≥1.00 D — consigliata verifica con refrazione oggettiva completa.")
            st.rerun()
        except Exception as e:
            st.error(f"Errore analisi immagine: {e}")
