# -*- coding: utf-8 -*-
"""Photoref AI — stima refrazione da foto del riflesso pupillare (photorefraction).
Screening qualitativo, NON sostituisce la refrazione oggettiva/soggettiva."""
from __future__ import annotations
import datetime
import hashlib, hmac, secrets as _sec
import io
import base64
import streamlit as st
import streamlit.components.v1 as components

try:
    import numpy as np
    from PIL import Image
    _HAS_DEPS = True
except Exception:
    _HAS_DEPS = False


def _token_secret():
    return str(st.secrets.get("privacy", {}).get("TOKEN_SECRET", "fallback_secret")).encode("utf-8")


def _ensure_link_table(conn):
    cur = conn.cursor()
    cur.execute("""
        CREATE TABLE IF NOT EXISTS photoref_link_token (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            paziente_id BIGINT NOT NULL REFERENCES pazienti(id) ON DELETE CASCADE,
            token_hash TEXT NOT NULL UNIQUE,
            created_at TIMESTAMP DEFAULT now(),
            expires_at TIMESTAMP,
            used_at TIMESTAMP
        )
    """)
    conn.commit()


def genera_link_cattura_mobile(conn, paziente_id: int, base_url: str, ttl_minutes: int = 30) -> str:
    """Crea un link mobile monouso valido ttl_minutes, senza login."""
    _ensure_link_table(conn)
    token = _sec.token_urlsafe(24)
    token_hash = hmac.new(_token_secret(), token.encode("utf-8"), hashlib.sha256).hexdigest()
    now = datetime.datetime.utcnow()
    exp = now + datetime.timedelta(minutes=ttl_minutes)
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO photoref_link_token (paziente_id, token_hash, created_at, expires_at) VALUES (%s,%s,%s,%s)",
        (paziente_id, token_hash, now.isoformat(), exp.isoformat()))
    conn.commit()
    return f"{base_url.rstrip('/')}/?photoref_token={token}"


def verifica_token_cattura(conn, token: str):
    """Ritorna paziente_id se il token è valido e non scaduto/usato, altrimenti None."""
    if not token:
        return None
    token_hash = hmac.new(_token_secret(), token.encode("utf-8"), hashlib.sha256).hexdigest()
    cur = conn.cursor()
    cur.execute("SELECT paziente_id, expires_at, used_at FROM photoref_link_token WHERE token_hash=%s", (token_hash,))
    row = cur.fetchone()
    if not row:
        return None
    pid, exp, used = (row.get("paziente_id"), row.get("expires_at"), row.get("used_at")) if hasattr(row, "get") else (row[0], row[1], row[2])
    if used:
        return None
    try:
        exp_dt = exp if isinstance(exp, datetime.datetime) else datetime.datetime.fromisoformat(str(exp))
        if datetime.datetime.utcnow() > exp_dt:
            return None
    except Exception:
        pass
    return pid


def marca_token_usato(conn, token: str):
    token_hash = hmac.new(_token_secret(), token.encode("utf-8"), hashlib.sha256).hexdigest()
    cur = conn.cursor()
    cur.execute("UPDATE photoref_link_token SET used_at=%s WHERE token_hash=%s",
                (datetime.datetime.utcnow().isoformat(), token_hash))
    conn.commit()


def _ensure_table(conn):
    cur = conn.cursor()
    cur.execute("""
        CREATE TABLE IF NOT EXISTS photoref_sessioni (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            paziente_id BIGINT NOT NULL REFERENCES pazienti(id) ON DELETE CASCADE,
            data_sessione DATE,
            stima_od REAL, stima_os REAL,
            asimmetria REAL,
            note TEXT,
            creato_il TIMESTAMP DEFAULT now()
        )
    """)
    conn.commit()
    for col, tipo in [("asse_od", "REAL"), ("asse_os", "REAL"),
                      ("working_distance_m", "REAL"), ("eccentricita_mm", "REAL")]:
        cur.execute(f"ALTER TABLE photoref_sessioni ADD COLUMN IF NOT EXISTS {col} {tipo}")
    conn.commit()


def _salva(conn, paz_id, data_s, stima_od, stima_os, asimmetria, note, asse_od=0, asse_os=0,
          working_distance_m=1.0, eccentricita_mm=20.0):
    cur = conn.cursor()
    cur.execute(
        """INSERT INTO photoref_sessioni (paziente_id, data_sessione, stima_od, stima_os, asimmetria, note,
                                          asse_od, asse_os, working_distance_m, eccentricita_mm)
           VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)""",
        (paz_id, data_s, stima_od, stima_os, asimmetria, note, asse_od, asse_os, working_distance_m, eccentricita_mm))
    conn.commit()


def _storico(conn, paz_id):
    cur = conn.cursor()
    cur.execute("""SELECT data_sessione, stima_od, stima_os, asimmetria
                   FROM photoref_sessioni WHERE paziente_id=%s ORDER BY data_sessione DESC""", (paz_id,))
    return cur.fetchall()


def _rileva_pupilla(gray: "np.ndarray"):
    """Individua il bordo della pupilla (disco scuro) nella regione centrale
    tramite soglia adattiva; ritorna (cy, cx, raggio_px) o None."""
    h, w = gray.shape
    cy0, cx0 = h // 2, w // 2
    win = min(h, w) // 2
    region = gray[max(0, cy0 - win):cy0 + win, max(0, cx0 - win):cx0 + win]
    if region.size == 0:
        return None
    # La pupilla nel riflesso è la macchia più scura circondata dall'iride;
    # sogliamo sotto la mediana per isolarla.
    thresh = np.percentile(region, 25)
    dark = region < thresh
    ys, xs = np.where(dark)
    if len(xs) < 20:
        return None
    cy = ys.mean() + max(0, cy0 - win)
    cx = xs.mean() + max(0, cx0 - win)
    raggio = (np.sqrt(len(xs) / np.pi))
    return cy, cx, raggio


def _analizza_riflesso(img: "Image.Image", occhio: str, working_distance_m: float = 1.0,
                        eccentricita_mm: float = 20.0):
    """Eccentric photorefraction (metodo Howland/Braddick, alla base dei
    photoscreener clinici tipo GoCheck Kids/PediaVision):
    - si individua la pupilla nel riflesso;
    - dentro il riflesso pupillare si cerca il crescent (mezzaluna) di luce:
      la sua estensione, come frazione del diametro pupillare, è proporzionale
      alla sfocatura (dioptrie) tramite l'eccentricità sorgente-obiettivo e la
      distanza di lavoro: D ≈ (crescent/diametro) * (eccentricità_mm/10) / working_distance_m;
    - la posizione del crescent (alto/basso/lato) rispetto al centro pupilla
      dà il segno/direzione (crescent sul lato opposto alla sorgente = miopia,
      stesso lato = ipermetropia) e l'asse approssimativo.
    Resta uno SCREENING qualitativo: la calibrazione va verificata con casi noti."""
    arr = np.asarray(img.convert("L"), dtype=float)
    pupilla = _rileva_pupilla(arr)
    if pupilla is None:
        return 0.0, 0.0, "Pupilla non rilevata — riscattare più vicino/più a fuoco"
    cy, cx, raggio = pupilla
    if raggio < 3:
        return 0.0, 0.0, "Pupilla troppo piccola nel campo — avvicinare il telefono"

    win = int(raggio * 1.4)
    y0, y1 = max(0, int(cy - win)), int(cy + win)
    x0, x1 = max(0, int(cx - win)), int(cx + win)
    disco = arr[y0:y1, x0:x1]
    if disco.size == 0:
        return 0.0, 0.0, "Regione pupillare non valida"

    # Crescent = pixel più luminosi dentro il disco pupillare
    soglia_luce = disco.mean() + 0.7 * disco.std()
    luce = disco > soglia_luce
    ys, xs = np.where(luce)
    if len(xs) == 0:
        return 0.0, 0.0, "Nessun riflesso luminoso rilevato — verificare flash e ambiente scuro"

    dcy, dcx = disco.shape[0] / 2, disco.shape[1] / 2
    off_y = (ys.mean() - dcy)
    off_x = (xs.mean() - dcx)
    estensione_crescent = np.sqrt(len(xs) / np.pi)  # raggio equivalente area luce
    frazione = estensione_crescent / max(raggio, 1e-6)

    stima_D = round(frazione * (eccentricita_mm / 10.0) / max(working_distance_m, 0.1), 2)
    # Segno: crescent spostato verso il basso/nasale nella foto standard (sorgente
    # sopra l'obiettivo) → ipermetropia; verso l'alto → miopia. Approssimazione.
    segno = 1.0 if off_y > 0 else -1.0
    stima_D *= segno

    asse = round((np.degrees(np.arctan2(off_y, off_x)) + 360) % 180)
    note_tecniche = f"Crescent {estensione_crescent:.1f}px su pupilla {raggio:.1f}px, asse ~{asse}°"
    return stima_D, asse, note_tecniche


_CAPTURE_HTML = """
<!DOCTYPE html><html><head><meta charset="utf-8"></head><body>
<div style="font-family:-apple-system,sans-serif;background:#0d1117;color:#e6edf3;padding:14px;border-radius:10px">
  <div style="display:flex;gap:8px;align-items:center;margin-bottom:10px">
    <span id="pr_step" style="font-weight:700">1/2 — Occhio destro (OD)</span>
    <span id="pr_dist" style="margin-left:auto;font-size:13px;color:#8b949e">Distanza: —</span>
  </div>
  <div style="position:relative;width:100%;max-width:420px;aspect-ratio:4/3;background:#000;border-radius:8px;overflow:hidden;margin:0 auto">
    <video id="pr_video" autoplay playsinline muted style="width:100%;height:100%;object-fit:cover"></video>
    <canvas id="pr_overlay" style="position:absolute;left:0;top:0;width:100%;height:100%"></canvas>
  </div>
  <canvas id="pr_shot" style="display:none"></canvas>
  <div style="display:flex;gap:10px;margin-top:12px;flex-wrap:wrap;justify-content:center">
    <button id="pr_torch" style="padding:10px 14px;border-radius:7px;border:none;background:#30363d;color:#fff;font-weight:600">🔦 Flash</button>
    <button id="pr_zoom_in" style="padding:10px 14px;border-radius:7px;border:none;background:#30363d;color:#fff;font-weight:600">🔍+ Zoom</button>
    <button id="pr_zoom_out" style="padding:10px 14px;border-radius:7px;border:none;background:#30363d;color:#fff;font-weight:600">🔍- Zoom</button>
    <button id="pr_capture" style="padding:10px 18px;border-radius:7px;border:none;background:#2ea44f;color:#fff;font-weight:700">📸 Scatta</button>
  </div>
  <div id="pr_msg" style="font-size:13px;color:#f0883e;margin-top:8px;text-align:center"></div>
  <div id="pr_preview" style="display:none;margin-top:12px;text-align:center">
    <img id="pr_img_od" style="max-width:140px;border-radius:6px;margin:4px" />
    <img id="pr_img_os" style="max-width:140px;border-radius:6px;margin:4px" />
  </div>
</div>
<script>
(function(){
  const video = document.getElementById('pr_video');
  const overlay = document.getElementById('pr_overlay');
  const octx = overlay.getContext('2d');
  const shot = document.getElementById('pr_shot');
  const msg = document.getElementById('pr_msg');
  const stepEl = document.getElementById('pr_step');
  let stream=null, track=null, zoomCap=null, zoomVal=1, torchOn=false, step=0;
  let shots=[null,null];

  function drawGuide(){
    octx.clearRect(0,0,overlay.width,overlay.height);
    octx.strokeStyle='#f0883e'; octx.lineWidth=3; octx.setLineDash([10,7]);
    octx.beginPath();
    octx.ellipse(overlay.width/2, overlay.height/2, overlay.width*0.18, overlay.height*0.28, 0, 0, 6.2832);
    octx.stroke();
  }

  async function start(){
    try{
      stream = await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment', width:{ideal:1280}, height:{ideal:960}}});
      video.srcObject = stream;
      await video.play();
      overlay.width = video.videoWidth||420; overlay.height = video.videoHeight||315;
      drawGuide();
      track = stream.getVideoTracks()[0];
      const caps = track.getCapabilities ? track.getCapabilities() : {};
      if (caps.zoom) zoomCap = caps.zoom;
      if (!caps.torch) document.getElementById('pr_torch').style.opacity='0.4';
      requestAnimationFrame(loop);
    }catch(e){
      msg.textContent = 'Impossibile avviare la fotocamera: ' + e.message + ' — consenti l\\'accesso e usa Chrome/Safari su HTTPS.';
    }
  }
  function loop(){ drawGuide(); requestAnimationFrame(loop); }

  document.getElementById('pr_torch').onclick = async ()=>{
    if(!track) return;
    torchOn = !torchOn;
    try{ await track.applyConstraints({advanced:[{torch:torchOn}]}); }
    catch(e){ msg.textContent='Flash non supportato su questo dispositivo.'; }
  };
  document.getElementById('pr_zoom_in').onclick = async ()=>{
    if(!track||!zoomCap) return;
    zoomVal = Math.min(zoomCap.max, zoomVal + (zoomCap.step||0.5));
    try{ await track.applyConstraints({advanced:[{zoom:zoomVal}]}); }catch(e){}
  };
  document.getElementById('pr_zoom_out').onclick = async ()=>{
    if(!track||!zoomCap) return;
    zoomVal = Math.max(zoomCap.min||1, zoomVal - (zoomCap.step||0.5));
    try{ await track.applyConstraints({advanced:[{zoom:zoomVal}]}); }catch(e){}
  };

  document.getElementById('pr_capture').onclick = ()=>{
    shot.width = video.videoWidth; shot.height = video.videoHeight;
    const sctx = shot.getContext('2d');
    sctx.drawImage(video, 0, 0);
    const cx = shot.width/2, cy = shot.height/2, rw = shot.width*0.20, rh = shot.height*0.30;
    const crop = document.createElement('canvas'); crop.width=rw*2; crop.height=rh*2;
    crop.getContext('2d').drawImage(shot, cx-rw, cy-rh, rw*2, rh*2, 0, 0, rw*2, rh*2);
    const dataUrl = crop.toDataURL('image/jpeg', 0.92);
    shots[step] = dataUrl;
    if (step===0){
      document.getElementById('pr_img_od').src = dataUrl;
      step = 1; stepEl.textContent = '2/2 — Occhio sinistro (OS)';
      msg.textContent = 'OD acquisito. Ora inquadra OS.';
    } else {
      document.getElementById('pr_img_os').src = dataUrl;
      document.getElementById('pr_preview').style.display='block';
      msg.style.color = '#7ee787';
      msg.textContent = 'Entrambe le foto acquisite. Invio in corso…';
      if(stream) stream.getTracks().forEach(t=>t.stop());
      const payload = JSON.stringify({od: shots[0], os: shots[1]});
      window.parent.postMessage({type:'photoref_capture', payload: payload}, '*');
    }
  };
  start();
})();
</script>
</body></html>
"""


def render_capture_mobile(conn, paz_id: int, token: str = None) -> None:
    """Link che apre la cattura guidata (flash, zoom, crop) in una scheda NUOVA,
    servita direttamente dal gestionale (Streamlit static serving) — un
    iframe/popup vuoto perde il permesso fotocamera, serve una pagina
    top-level reale sullo stesso dominio del gestionale."""
    import urllib.parse, time
    st.markdown("### 📸 Photoref AI — Cattura guidata")
    st.caption("Si apre in una scheda separata (necessario per il permesso fotocamera). "
              "Tieni il telefono a ~40 cm dal viso, ambiente poco illuminato.")
    q = urllib.parse.urlencode({"v": str(int(time.time()))})
    url = f"/app/static/photoref_capture.html?{q}"
    st.markdown(
        f'<a href="{url}" target="_blank" rel="noopener" '
        'style="display:inline-block;padding:11px 18px;border-radius:8px;'
        'background:#2ea44f;color:#fff;font-weight:bold;text-decoration:none;'
        'font-size:15px">📸 Apri cattura guidata (scheda nuova)</a>',
        unsafe_allow_html=True)
    st.caption("Scatta OD e OS: le 2 foto si scaricano da sole, poi caricale qui sotto per l'analisi.")


def render_photoref(conn, paz_id: int, paziente: dict = None) -> None:
    st.subheader("📸 Photoref AI — Stima refrazione")
    st.caption("Screening qualitativo da foto del riflesso pupillare (tipo photoscreener). "
              "Non sostituisce autorefrattometro, schiascopia o refrazione soggettiva.")
    if not _HAS_DEPS:
        st.error("Dipendenze mancanti (pillow, numpy) — aggiungerle a requirements.txt per attivare l'analisi.")
        return

    try:
        _ensure_table(conn)
        _ensure_link_table(conn)
    except Exception as e:
        st.error(f"Impossibile preparare la tabella: {e}")
        return

    st.markdown("##### 📱 Genera link cattura mobile (guidata, con flash/zoom)")
    base_url = st.text_input("URL pubblico del gestionale", "https://gestionale-the-organism.streamlit.app", key="pr_base_url")
    ttl = st.number_input("Validità link (minuti)", 5, 180, 30, 5, key="pr_ttl")
    if st.button("🔗 Genera link", key="pr_gen_link"):
        url = genera_link_cattura_mobile(conn, paz_id, base_url, int(ttl))
        st.code(url, language="text")
        st.caption("Apri questo link sul telefono del paziente/operatore: guida flash+zoom+distanza, poi le foto tornano qui.")
    st.markdown("---")

    rows = _storico(conn, paz_id)
    if rows:
        st.markdown("#### Storico stime")
        for r in rows:
            data_s, s_od, s_os, asim = (r.get(k) if hasattr(r, "get") else r[i]
                                        for i, k in enumerate(["data_sessione","stima_od","stima_os","asimmetria"]))
            st.caption(f"📅 {data_s} · Stima OD {s_od:+.2f} D · OS {s_os:+.2f} D · Asimmetria {asim:.2f} D")

    st.markdown("---")
    st.markdown("#### Carica foto (o usa il link mobile sopra e poi carica qui il risultato)")
    c1, c2 = st.columns(2)
    with c1:
        foto_od = st.file_uploader("Foto riflesso OD", type=["jpg","jpeg","png"], key="photoref_od")
    with c2:
        foto_os = st.file_uploader("Foto riflesso OS", type=["jpg","jpeg","png"], key="photoref_os")

    st.markdown("**Parametri di scatto** (necessari per convertire il crescent in diottrie)")
    c1, c2 = st.columns(2)
    working_distance_m = c1.number_input("Distanza di lavoro (m)", 0.3, 3.0, 1.0, 0.1, key="photoref_wd")
    eccentricita_mm = c2.number_input("Eccentricità flash-obiettivo (mm)", 5.0, 40.0, 20.0, 1.0, key="photoref_ecc",
                                      help="Distanza tra il flash del telefono e l'obiettivo della fotocamera.")

    data_s = st.date_input("Data sessione", datetime.date.today(), key="photoref_data")
    note = st.text_area("Note (distanza, illuminazione, collaborazione paziente)", "", height=68, key="photoref_note")

    if st.button("🔍 Analizza e salva", type="primary", key="photoref_analizza"):
        if not foto_od or not foto_os:
            st.warning("Carica entrambe le foto (OD e OS) prima di analizzare.")
            return
        try:
            img_od = Image.open(io.BytesIO(foto_od.read()))
            img_os = Image.open(io.BytesIO(foto_os.read()))
            stima_od, asse_od, note_od = _analizza_riflesso(img_od, "OD", working_distance_m, eccentricita_mm)
            stima_os, asse_os, note_os = _analizza_riflesso(img_os, "OS", working_distance_m, eccentricita_mm)
            asimmetria = round(abs(stima_od - stima_os), 2)
            _salva(conn, paz_id, data_s.isoformat(), stima_od, stima_os, asimmetria, note,
                  asse_od, asse_os, working_distance_m, eccentricita_mm)
            st.success(f"Stima OD {stima_od:+.2f} D (asse {asse_od}°) · OS {stima_os:+.2f} D (asse {asse_os}°) · Asimmetria {asimmetria:.2f} D")
            st.caption(f"OD: {note_od}")
            st.caption(f"OS: {note_os}")
            if asimmetria >= 1.0:
                st.warning("⚠️ Asimmetria ≥1.00 D — consigliata verifica con refrazione oggettiva completa.")
            st.rerun()
        except Exception as e:
            st.error(f"Errore analisi immagine: {e}")
